projects:
  graphql:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        graphQLApiId: qmmqrzhiijeddek2rwkx7eyj54
      endpoints:
        prod: >-
          https://ordpjmzne5gi7icb65wbxqxhwe.appsync-api.us-east-1.amazonaws.com/graphql
